appId: com.mycompany.myapp
productName: MyApp
files:
  - dist/**/*
  - "!dist/bin"
directories:
  output: dist/bin
win:
  target: nsis
mac:
  category: public.app-category.business
  publish: null
linux:
  target: tar.gz